### ISSUE TITLE
Описание работы

### ISSUE THREAD

**Issue by victor-yacovlev** [mipt-proglang-2015/proglangs_biktimirov#4]
ОК, оно запустилось.

И как дальше пользоваться?

![snapshot5](https://cloud.githubusercontent.com/assets/1440088/11812391/af6956e6-a34c-11e5-83db-d3a6f257ba9f.png)

**Comment by victor-yacovlev** [comment]
См. https://yadi.sk/i/Jpg370jPmFBeh

**Comment by aidarbiktimirov** [comment]
У вас последняя версия кода?
Вот [тут](http://biktimirov.net/tictactoe/) создается
